export const GOLD_CATEGORIES: ReadonlyArray<{
  slug: string;
  weight: "gold" | "high" | "medium";
}> = [
  // Official Roblox content
  { slug: "announcements", weight: "gold" },
  { slug: "updates", weight: "gold" },
  { slug: "release-notes", weight: "gold" },
  { slug: "roblox-engineers", weight: "gold" },
  { slug: "public-roadmap", weight: "gold" },
  { slug: "engine-features", weight: "gold" },
  { slug: "studio-features", weight: "gold" },

  // Curated community knowledge
  { slug: "resources", weight: "high" },
  { slug: "community-resources", weight: "high" },
  { slug: "community-tutorials", weight: "high" },
  { slug: "developer-discussion", weight: "high" },
  { slug: "cool-creations", weight: "high" },

  // Tech support / Q&A (where solutions live)
  { slug: "scripting-support", weight: "medium" },
  { slug: "code-review", weight: "medium" },
  { slug: "help-and-feedback", weight: "medium" },
  { slug: "technical-base", weight: "medium" },
  { slug: "platform-usage-support", weight: "medium" },

  // Bug reports (often have engineer replies with engine internals)
  { slug: "studio-bugs", weight: "medium" },
  { slug: "engine-bugs", weight: "medium" },
  { slug: "client-bugs", weight: "medium" },
  { slug: "mobile-bugs", weight: "medium" },
  { slug: "website-bugs", weight: "medium" },
  { slug: "bug-reports", weight: "medium" },

  // Design / asset support
  { slug: "art-design-support", weight: "medium" },
  { slug: "building-support", weight: "medium" },
  { slug: "game-design-support", weight: "medium" },
  { slug: "ui-design-support", weight: "medium" },
  { slug: "audio-design-support", weight: "medium" },
  { slug: "animation-support", weight: "medium" },
];

export const EXPANDED_QUERIES = [
  // Luau language + runtime
  "Luau performance",
  "Luau native codegen",
  "Luau type checking",
  "strict types",
  "type solver",
  "generalized iteration",
  "buffer library",
  "buffer create",
  "bit32",
  "vector library",
  "string pack",
  "table.freeze",
  "table.clone",
  "shared table",
  "SharedTable",
  "coroutine",
  "task.spawn",
  "task.defer",
  "task.delay",
  "task.synchronize",
  "task.desynchronize",
  "pcall xpcall",
  "debug.traceback",
  "garbage collection",
  "memory leak",
  "weak table",

  // Profiling and optimization
  "MicroProfiler",
  "script performance",
  "server performance",
  "render performance",
  "frame time",
  "DevConsole",
  "BasePart optimization",
  "mesh optimization",
  "texture optimization",
  "draw calls",
  "instance streaming",
  "StreamingEnabled",
  "streaming radius",
  "content streaming",
  "PerformanceStats",

  // Parallel / concurrency
  "Parallel Luau",
  "Actor",
  "ParallelScheduler",
  "deferred events",
  "signal behavior",

  // Networking and replication
  "RemoteEvent security",
  "RemoteFunction",
  "UnreliableRemoteEvent",
  "BindableEvent",
  "replication priority",
  "network ownership",
  "raknet",
  "server tick",
  "NetworkClient",
  "NetworkServer",
  "HttpService",
  "http request",

  // Persistence
  "DataStore",
  "DataStoreService",
  "OrderedDataStore",
  "DataStore2",
  "ProfileStore",
  "ProfileService",
  "MemoryStore",
  "MemoryStoreSortedMap",
  "MemoryStoreQueue",
  "MemoryStoreHashMap",
  "session locking",
  "data loss",
  "OpenCloud",
  "Open Cloud DataStore",
  "MessagingService",

  // Physics / movement
  "PhysicsService",
  "physics steps",
  "humanoid controller",
  "character controller",
  "AvatarAbilities",
  "Animator",
  "animation streaming",
  "IKControl",
  "AlignPosition",
  "AlignOrientation",
  "LinearVelocity",
  "AngularVelocity",
  "VectorForce",
  "Constraint",
  "BodyMover deprecation",
  "PathfindingService",
  "PathfindingModifier",
  "raycast",
  "shapecast",
  "spatial query",
  "OverlapParams",

  // Geometry / world
  "CFrame math",
  "Vector3",
  "Region3",
  "WorldRoot",
  "Workspace folders",
  "PivotTo",

  // Lighting / FX
  "Lighting",
  "Atmosphere",
  "future lighting",
  "shadow map",
  "post processing",
  "ColorCorrection",
  "Bloom",
  "DepthOfField",
  "ParticleEmitter",
  "Beam",
  "Trail",

  // Audio
  "SoundService",
  "new audio API",
  "AudioPlayer",
  "AudioEmitter",
  "AudioListener",
  "AudioDeviceOutput",

  // UI
  "ScreenGui",
  "SurfaceGui",
  "BillboardGui",
  "UIListLayout",
  "UIGridLayout",
  "UIPadding",
  "UIStroke",
  "UICorner",
  "UIScale",
  "ScrollingFrame",
  "GuiObject input",
  "AutoLocalize",
  "TweenService",

  // Avatar / marketplace
  "HumanoidDescription",
  "Accessory",
  "AvatarEditorService",
  "MarketplaceService",
  "GamePass",
  "developer product",
  "badges",

  // Studio / assets / tooling
  "Studio plugin api",
  "Studio command bar",
  "AssetService",
  "InsertService",
  "EditableMesh",
  "EditableImage",
  "DraftsService",
  "team create",
  "collaborative editing",

  // Frameworks / packages
  "Knit framework",
  "Matter ecs",
  "Roact",
  "Fusion ui",
  "Nevermore",
  "AeroGameFramework",
  "Janitor",
  "Maid",
  "Trove",
  "Signal class",
  "ReplicaService",
  "Wally package",
  "Rojo workflow",
  "Foreman",
  "Aftman",
  "Lune",
  "roblox-ts",
  "RoStrap",

  // Collections / data structures
  "CollectionService",
  "AttributeChangedSignal",
  "linked list luau",
  "ring buffer luau",

  // Security
  "exploit mitigation",
  "server validation",
  "anti exploit",
  "secure teleport",
  "hmac signature",
  "input sanitization",
  "FilteringEnabled",

  // AI / LLM tooling
  "Roblox Assistant",
  "Code Assist",
  "AI generation",
];
